ARDUINO_QUIET = 1
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = ../externals/Arduino-Makefile/
AVR_TOOLS_DIR = /usr
MONITOR_PORT  = /dev/ttyACM0
BOARD_TAG    = teensy31
ARDUINO_LIBS = Wire SoftwareSerial 

include $(ARDMK_DIR)/Teensy.mk
